name: shoppify
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  animated_text_kit: ^4.2.3
  easy_localization: ^3.0.8
  flutter:
    sdk: flutter
  gap: ^3.0.1
  smooth_page_indicator: ^1.2.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - localization/
  fonts:
    - family: Suwannaphum
      fonts:
        - asset: assets/fonts/Suwannaphum-Regular.ttf
        
          
